module.exports = {
  projects: [
    '<rootDir>/libs/xplat/core',
    '<rootDir>/libs/xplat/features',
    '<rootDir>/libs/xplat/scss',
    '<rootDir>/libs/xplat/utils',
    '<rootDir>/libs/xplat/web/core',
    '<rootDir>/libs/xplat/web/features',
    '<rootDir>/libs/xplat/web/scss',
    '<rootDir>/apps/web-myapp',
    '<rootDir>/libs/xplat/nativescript/scss',
    '<rootDir>/libs/xplat/nativescript/utils',
    '<rootDir>/libs/xplat/nativescript/core',
    '<rootDir>/libs/xplat/nativescript/features',
    '<rootDir>/libs/xplat/ionic/core',
    '<rootDir>/libs/xplat/ionic/features',
    '<rootDir>/libs/xplat/ionic/scss',
    '<rootDir>/libs/xplat/electron/core',
  ],
};
